# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='lastfetch',
            field=models.DateTimeField(null=True),
        ),
    ]
