# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_auto_20170524_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='port',
            field=models.SmallIntegerField(default=4443),
        ),
    ]
